---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: web
spec:
  encryptedData:
    password: AgAHoad5dPQrboTzSu36UYwJwb4mUnAy1YSPmBYD3C1np/HX4En45TG+o1iXSC3Sww/nkm2Yr157Fos8o5YUJJBA4i3C4mjWKgJdwpBYnqd/6BaPdp4ak6SSzw1Jx4EV8dxO5qWqf3t+zUtXiKOzivCb2J1hyjb0B7Oron+6zqcZH43YHYYoDuUOIleD7O++qL2nTvvQJIKNKMBWCZpnObtg3lB1AjVyQHPEV375vmCSvdlxdqZH3CWNScm3+RLX9AJyza/c85sOzlAwOGUaq2eOGcsLvM+ylM2AZd+k0Tqcx0m9zeXeA332AfWBIEuAbb12vfMaqktHSHcH7xFItDRqWSojAqpND6ScwlM18EK8mQ1+BXMgjUOw+tN+vIuUXFfmS7UZslXwUM2UKeX/UfzCg/79XKZxizAxDuJn5Hy6a2WZ/c7V1syTVSrUk3JgYVGgYjuhy8AbL7xapSy8y/PFanG5Ex5y0KzazuQgn8n+2MvsotYlHTfofypvxHWNJsvIvfYVzdZVI/p0WonLzreEuif1gojRJi6mMCs/tG4OZEnl0WnP0Z3F6q0AklObQmvG7cSSkFIVZN/fu1KBr8u5IFNFJ7gVTjj+c11GejqONVVDw8gr4CrOteOjTA+rTZV8Q46fzBH6ZtVTresbf16vq9FEb0h/ZG1uEKEVDmRowZ6vL+V0kOt9l2IoLVGd0fOfFLNa8C6wb9nUu5kkmw==
    username: AgBflmPhAub3vWGOVvW0Xgg3BmpxK2Y9xT5KzEcpDSQ1SN4JQMMstHElaTbfBt8fKk7PwXq9/uktN3/K9qJ0cASN76ZHfG4KkzqzpbSPUJMavZtQjcX7C0foS2KJUCr92qvdZZBUOtaMOlo31eNfGf0BIziM8qZLyXYiT3reV5+TKhSDOXKKQ3ym3yDm4d06To/Elnz4Jcw6YgYkJ+rEX/gN0wtrALdsiI2p4d98wNNcBaIohdwLRT35b0CldIXp+u/jJSrXUtF6TW36b0f9n/sSQoRaTKoqgTG6W7fWQbo6s4x47T/Ztb0msT1eXtu1j7Zp4/6UcT8LCYNqur8xpmSHAhP0XrunIi6gYjiFJRjMFzXWgWJiBNgz5KdtjBnr5l64jRjXbhu9/xtpLndmH5fg7KcjkJzoJIBF3W0xYQ1zT9Df52hvaFIebNEHNVe/IjRinPm4euLDqYQxdODFBEZ7Xp6nGRHEI4kLwj98QNg0qpXMiBoVJOZakfOoZz1JXAXQ1vnbHKDCQjnVA45lRfV/wmBQ2S5rOe4NILt6MPZgUvn6D04bkyTFWnI36uzYq6YocfuL4J8jf2s4HE170rLusDnELgt1WbyvP34xJKaZ4TGLkgNePhIKVbEYi8baEU3dg3RUlzkhoSu61pajzFdQlYOWAcXN4BeNmPx3jUWueR2m9ncdxIG0m4/Z3HgwRhVDcdHO0g==
  template:
    metadata:
      name: db-credentials
      namespace: web
