apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: web
type: Opaque
stringData:              # plaintext in Git; fine for learning. For prod: Sealed Secrets/External Secrets.
  username: "myuser"
  password: "mypassword"

