---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: web
spec:
  encryptedData:
    password: AgAnoChcyrveqC5lHnxTp97Tj2Wu2dMxp07tqsJVm4Yk/a3WAqtGVRxavsG6hY/GbNXnEQE/VnP1irYagWcYifPhTubuB33EdC9Vv0ZyFRfUwitdQ7/GBtEjYvceez/d5FFEOi081PO+SyKdoIMqPl/BTR5YHFiZ0y+RVbQX2fjVQsGBNr0nyykC4Ys3pqMc3clNf07aUBIUMqSsCJ3koyw+VKmJTPjo52m4hAd/bbAjArgR96vqzH0zg4BpBg3SCEy0+f7+4an9QuHXkJ1uNfYitWMUE4O7c43D0ghISS3dDwwCvupj7Ox7ove8Tx3kr9ZrwBc3gahX+iSLWBSsPoh3XlxdUvZApLIAumBuCav89jh+1vt8xkt1s9YJGj+ti1g/wj5qhPKZogKbPjHE9wv9k9kmVnZbaUOUDDkL13QOhD8FTEXk7B4PgtE763tJNhJvcLOaDmLPWc5b6UK434jUIRdHJCNoG6fjuvo5NLNFfmfLkz7RrwTJn9PBBDCnXTWUztdvFWvjRAwU+YSliKgwknjKgH95Lw0mRcWOvl9hHtvdOuQKLq2OEtqyriYEb6vIxMByiNCnqHUFJnvrEBi30s4RWj9vVYWJxPzlFfyXCbeu5K06ovrf+EXDkXlHnR3zTNkOrDPMSRxbKSMwlTXdqOXE9WaYY5XpCGFdOmPk1E0qm4Vyf8J0iYbE+Nm/oR7ympwIgBxreQsP01FjSA==
    username: AgBXqR2U56oxCGcUP6yLlScEhdK/t1vgnrT0fc/2tn8gRT560s8LT1wqz/Wq32dfCNGQap5Qb7XJfwXW53n4xYnc3g5oaQJI1iboE22F5gTP8KEQuyqPGwwCllR+qBM/yxIiApjFwrpMBIJW9kJrULfHRNeVvn4T4KrfG4kTOXjUOb8tbaGLcwOdvkGeGxy+MeRODeKCHc3DqjhdC8Xe95r6e0QtIXzO1qFkzsNCbs3x9NlBx6LgGh67EOsMcCiV/sklAhNrZkY542f2xWT1Aq0/yKZ0bUd8yMCqzvxt+kftHDsKR6wrMUvCeqlkLwc0eyIUrPVRKUrCEmsx3B3tTyqxj8FGA5RUvg0fLFfRCVFD3Njuw0pyeAPVW08orlcr4+/dyo2Civt+4fh+qj/c0QZcNwZA1pru+2xIqC9KWSh/fpiS6q2U+WdfHOLthws8l1TeLkfhsZRBBJe9ZFbfxbTZtsX7YUcR7OU8Is1hD2iViRQEpn9GuMRezvNvMkbKthunygnpF0kyrPruq/o03RrLOkblkCOXhL9vzQNbhINCR24yJTT4leaN880NdgRIPVAEaJDpwuxwcNkICITLpajnXJmbLWN9ywJOGW8X0+cBlvUQ0mX4MdXYPG/YYdkVedFpVfte9IKFFG4QcAqqTDl8hvzcKuoVM+JWRHDP8/PprR61gLi2to41W5gsYht56VygD8Op3g==
  template:
    metadata:
      name: db-credentials
      namespace: web
